section .text
  global _start
_start:
  mov rax, 0AFFFFFFFFFFFFFFBh
  mov rbx, 0AFFFFFFFFFFFFFFBh
  mov rcx, 0AFFFFFFFFFFFFFFBh
  mov rdx, 0AFFFFFFFFFFFFFFBh
  mov rsi, 0AFFFFFFFFFFFFFFBh
  mov rdi, 0AFFFFFFFFFFFFFFBh
  mov r8, 0AFFFFFFFFFFFFFFBh
  mov r9, 0AFFFFFFFFFFFFFFBh
  mov r10, 0AFFFFFFFFFFFFFFBh
  mov r11, 0AFFFFFFFFFFFFFFBh
  mov r12, 0AFFFFFFFFFFFFFFBh
  mov r13, 0AFFFFFFFFFFFFFFBh
  mov r14, 0AFFFFFFFFFFFFFFBh
  mov r15, 0AFFFFFFFFFFFFFFBh

